[package]
name = "postage"
version = "0.1.0"
description = "An async channel library"
keywords = ["async", "channels"]
categories = ["asynchronous"]
authors = ["Austin Jones <implAustin@gmail.com>"]
edition = "2018"
homepage = "https://github.com/austinjones/postage-rs"
repository = "https://github.com/austinjones/postage-rs"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project = "1"
crossbeam-queue = "0.3"
atomic = "0.5"
futures-task = "0.3"

[dev-dependencies]
futures-test = "0.3"